/** * @jest-environment jsdom */
/// <reference types="Jest"/>
import constructorPokemon from '../pokemon';
import bulbasaur from './fixtrures/bulbasaur.json';

test('prueba que construir pokemon funcione correctamente', () => {
  expect(constructorPokemon(bulbasaur)).toMatchObject({
    id: 1,
    nombre: 'bulbasaur',
    peso: 69,
    altura: 7,
    habilidades: [' "overgrow"', ' "chlorophyll"'],
    tipos: [' "grass"', ' "poison"'],
    movimientos: [
      ' "razor-wind"',
      ' "swords-dance"',
      ' "cut"',
      ' "bind"',
      ' "vine-whip"',
      ' "headbutt"',
      ' "tackle"',
      ' "body-slam"',
      ' "take-down"',
      ' "double-edge"',
      ' "growl"',
      ' "strength"',
      ' "mega-drain"',
      ' "leech-seed"',
      ' "growth"',
      ' "razor-leaf"',
      ' "solar-beam"',
      ' "poison-powder"',
      ' "sleep-powder"',
      ' "petal-dance"',
      ' "string-shot"',
      ' "toxic"',
      ' "rage"',
      ' "mimic"',
      ' "double-team"',
      ' "defense-curl"',
      ' "light-screen"',
      ' "reflect"',
      ' "bide"',
      ' "sludge"',
      ' "skull-bash"',
      ' "amnesia"',
      ' "flash"',
      ' "rest"',
      ' "substitute"',
      ' "snore"',
      ' "curse"',
      ' "protect"',
      ' "sludge-bomb"',
      ' "mud-slap"',
      ' "giga-drain"',
      ' "endure"',
      ' "charm"',
      ' "swagger"',
      ' "fury-cutter"',
      ' "attract"',
      ' "sleep-talk"',
      ' "return"',
      ' "frustration"',
      ' "safeguard"',
      ' "sweet-scent"',
      ' "synthesis"',
      ' "hidden-power"',
      ' "sunny-day"',
      ' "rock-smash"',
      ' "facade"',
      ' "nature-power"',
      ' "ingrain"',
      ' "knock-off"',
      ' "secret-power"',
      ' "grass-whistle"',
      ' "bullet-seed"',
      ' "magical-leaf"',
      ' "natural-gift"',
      ' "worry-seed"',
      ' "seed-bomb"',
      ' "energy-ball"',
      ' "leaf-storm"',
      ' "power-whip"',
      ' "captivate"',
      ' "grass-knot"',
      ' "venoshock"',
      ' "round"',
      ' "echoed-voice"',
      ' "grass-pledge"',
      ' "work-up"',
      ' "grassy-terrain"',
      ' "confide"',
    ],
  });
});
